{% set version = "0.3.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gtable
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gtable_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gtable/gtable_{{ version }}.tar.gz
  sha256: 2f9a58d978e2a487b7fd8841539ea33cf948e55ddf6f7a9bd2dd3362600a7b3a

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-glue
    - r-lifecycle
    - r-rlang
  run:
    - r-base
    - r-cli
    - r-glue
    - r-lifecycle
    - r-rlang

test:
  commands:
    - $R -e "library('gtable')"           # [not win]
    - "\"%R%\" -e \"library('gtable')\""  # [win]

about:
  home: https://gtable.r-lib.org
  dev_url: https://github.com/r-lib/gtable
  license: MIT
  summary: Tools to make it easier to work with "tables" of 'grobs'. The 'gtable' package defines a 'gtable' grob class that specifies a grid along with a list of grobs and their placement in the grid. Further the package makes it easy to manipulate and combine 'gtable' objects so that  complex compositions can be build
    up sequentially.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
