appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PzNA5mrePfTH8knUyATsOTFAwzSIBO2UbQgFRcyFQKR7VdZjUqXqU5xWsD9WapUx1R6SC3/aWp05GFpWYec8rMNBrkQcQnFs12W+9s2JPRS3ZZVoMu6HoPjJp914zP+KfdXwF+IhojAiJwGHlostKLQgPD4nfRGLQhWSS0n6kAayVwhmyGAnnvyWJs0voY/TMElqRtq7m2c35I+eMoFTWE4+qUrt29ny90i0XxWeAE0VlrnQZKsbmDwADpb7V651jBytO7HtcVNVqsUdFQ1OlrCPHlbYPbXCfQs638VXNtrHViQ1haigafXMh60Q7tyR6067L+jsWQBiVqCjFJMHOnQAcOkdvRCraBvpbt6mXb6osjw2e0DAVsVJegxwfbez0xdjSW8KyYhkOikaGrLrDScZNnbHYj8WYS5ZLL+OFlyPk8c8nxVXT+5dTzUwmeBNuNh8UKox0GUoikAYKwlDi4+idIyxX8HSQAWkg+lClA7JFRU/76AiCxXLxdkN5VLS9sviiXt9Y9IwiKWztlh89nSzcYvTHx5jRGUiG1JRxtORbqpVGGT4/QE2Ky3vZIsARJ3thWWX6ATNkUqDxTFIyPWxDZCOTe5xUPkSYYg0MPQ8qpAiE7Zzxa7/y+bXXUNqdGYQJ0q/ZzT+5qvmuw7CX8FKoDW/knGziO/tlpdbldE=}
